name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      fail-fast: false
      matrix:
        container:
          - alpine:latest
          - ubuntu:latest
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: dtm --help
